### PR TITLE
0.10.4.2-r7: allow bytestring-0.12 and text-2.1, bump CI to GHC 9.8.0

### PR DESCRIPTION
**Pull request by andreasabel**
Published revision 7 to hackage: https://hackage.haskell.org/package/safecopy-0.10.4.2/revisions/

### CODE REVIEW

**Comment by andreasabel** [comment]
@stepcut: Could you add me to the `acid-state` organization?  
Then I could merge such maintenance PRs myself.

**Comment by ddssff** [comment]
I second the motion.

**Comment by andreasabel** [comment]
I updated this PR to revision 8 with bumps for GHC 9.8.1.  
Published revision 8 to hackage: https://hackage.haskell.org/package/safecopy-0.10.4.2/revisions/

**Comment by andreasabel** [comment]
@stepcut: Any news on this?

**Pull request merged**
