### PR TITLE
Implement typeable-based default

### LINKED ISSUE #64: errorTypeName method has sensible default implementation
Using `DefaultSignatures`, the `errorTypeName` method could easily be given the implementation:

```haskell
    default errorTypeName :: (Typeable a) => Proxy a -> String
    errorTypeName prxy = show (typeRep prxy)
```

Since all types are `Typeable` in recent GHC, this would be trivially satisfiable for all types.

### PR DESCRIPTION
**Pull request by parsonsmatt**
This PR implements a `Typeable`-based default implementation of `errorTypeName` for better error messages. This implementation uses CPP to preserve GHC < 7.2 compatibility.

Resolves #64

### CODE REVIEW

**Comment by ddssff** [comment]
Are we ok with dropping ghc-7.8 support?  I am.

**Comment by Lemmih** [comment]
Fine by me.

**Comment by parsonsmatt** [comment]
If we're going to only support >=8.0 then I'll submit a PR without the CPP :)

**Comment by ddssff** [comment]
We should keep 7.10 - some people still use the ghcjs version based on it.

**Comment by parsonsmatt** [comment]
OK, it passes CI on GHC >=7.10 :) I regenerated the travis.yml with newer point versions as well (and the newer script), can revert that one if y'all want.

**Pull request closed without merging**
