### PR TITLE
Fixes instance generation for types containing tuples(TH 2.10.0)

### LINKED ISSUE #23: deriveSafeCopy broken with template-haskell 2.10.0 and tuple types
Minimal code to reproduce:
```haskell
{-# LANGUAGE TemplateHaskell #-}

import Data.SafeCopy

newtype IntPair = IntPair (Int, Int)

deriveSafeCopy 0 'base ''IntPair
```

It fails to compile with:
```
Main.hs:7:1:
    Illegal variable name: ‘safePut_(,)IntInt’
    When splicing a TH declaration:
      instance Data.SafeCopy.SafeCopy.SafeCopy Main.IntPair
    where Data.SafeCopy.SafeCopy.putCopy (Main.IntPair arg_0) = Data.SafeCopy.SafeCopy.contain (do {safePut_(,)IntInt_1 <- Data.SafeCopy.SafeCopy.getSafePut;
                                                                                                    safePut_(,)IntInt_1 arg_0;
                                                                                                    GHC.Base.return ()})
          Data.SafeCopy.SafeCopy.getCopy = Data.SafeCopy.SafeCopy.contain (Data.Serialize.Get.label "Main.IntPair:" (do {safeGet_(,)IntInt_2 <- Data.SafeCopy.SafeCopy.getSafeGet;
                                                                                                                         GHC.Base.return Main.IntPair GHC.Base.<*> safeGet_(,)IntInt_2}))
          Data.SafeCopy.SafeCopy.version = 0
          Data.SafeCopy.SafeCopy.kind = Data.SafeCopy.SafeCopy.base
          Data.SafeCopy.SafeCopy.errorTypeName _ = "Main.IntPair"
```

### PR DESCRIPTION
**Pull request by dredozubov**
closes #23 
Left some extra bits - felt like a right thing to do this time. Will get rid of them if it's needed.

### CODE REVIEW

**Comment by dredozubov** [comment]
Can someone please get a look at this? It's impossible to build one of my projects w/o add-source right now.

cc @Lemmih @dmjio

**Comment by dredozubov** [comment]
@Lemmih can you consider bumping version and uploading new version(including this patch) to hackage?

**Comment by Lemmih** [comment]
Do you want to do it? I'll add you as a maintainer if you want.

**Comment by dmjio** [comment]
I'm on vacation in Japan, but I could do it tomorrow, unless @dredozubov wants to.

**Comment by dmjio** [comment]
https://github.com/acid-state/safecopy/commit/fd55b5ba387bab7f9c0a4bda9313ebf3aef8d625 is now on hackage

**Comment by dredozubov** [comment]
@dmjio Thanks, David!

**Pull request merged**
