### PR TITLE
Various GHC 7.10 fixes

### PR DESCRIPTION
**Pull request by bgamari**

### CODE REVIEW

**Comment by bgamari** [comment]
Correct me if I'm wrong but I don't believe the test failures are due to my work.

**Comment by bgamari** [comment]
Ping.

**Comment by Lemmih** [comment]
I won't have time for maintenance for a few months still.

Does anyone know why Travis is complaining?

**Comment by bgamari** [comment]
@Lemmih the problem appears to be the fact that `lens` no longer includes the monadic lens combinators (e.g. `(^!!)`).

**Pull request merged**
