### PR TITLE
Depend upon lens-action for tests

### PR DESCRIPTION
**Pull request by bgamari**
Monadic lenses have been moved out of lens

### CODE REVIEW

**Comment by Lemmih** [comment]
Still broken, it seems.

**Comment by bgamari** [comment]
@Lemmih fixed.

**Comment by bgamari** [comment]
It would be great if you could cut a release with these fixes.

**Comment by Lemmih** [comment]
Try poking the other maintainers. Sup @dag @dmjio ?

**Comment by dmjio** [comment]
I can push it later today.

**Comment by dmjio** [comment]
pushed, http://hackage.haskell.org/package/safecopy

**Pull request merged**
