### PR TITLE
add ghc-8.2.1 to travis build

### PR DESCRIPTION
**Pull request by int-e**
It's sufficient to just bump dependecies.

### CODE REVIEW

**Comment by int-e** [comment]
The tests are still broken with ghc-8.2, because of the time dependency of quickcheck-instances. A bump is already in the pipeline according to https://github.com/aslatter/qc-instances/pull/30 but not released on hackage.

Without --enable-tests, the package can already be installed.

**Comment by RyanGlScott** [comment]
The tests might work now that [`quickcheck-instances-0.3.13`](http://hackage.haskell.org/package/quickcheck-instances-0.3.13) has been released, which supports GHC 8.2.

**Comment by niteria** [comment]
+1

**Comment by int-e** [comment]
Indeed the package builds fine with ghc-8.2.1 now

**Comment by int-e** [comment]
bump, ghc-8.2.1 is now released

**Comment by hvr** [comment]
@RyanGlScott @niteria @int-e This has been stalling for a long time; if you any of you has taken a look at the code and can vouch for that it's safe (sic) to relax the bounds for `safecopy`, I'll go ahead and relax upper bounds!

**Comment by RyanGlScott** [comment]
Looks like this was fixed in [`safecopy-0.9.3.3`](http://hackage.haskell.org/package/safecopy-0.9.3.3).

**Pull request merged**
