### PR TITLE
safecopy: Update for template-haskell 2.11

### PR DESCRIPTION
**Pull request by bgamari**
Shipped with GHC 8.0.1

### CODE REVIEW

**Comment by aycanirican** [comment]
@dmjio ping

**Comment by stepcut** [comment]
The TH changes look good. The `safecopy.cabal` file still has `template-haskell < 2.11`. Is there any reason not to bump that up to '< 2.12' so that the changes can actually be used?

**Comment by bgamari** [comment]
Jeremy Shaw <notifications@github.com> writes:

> The TH changes look good. The `safecopy.cabal` file still has
> `template-haskell < 2.11`. Is there any reason not to bump that up to
> '< 2.12' so that the changes can actually be used?
>
Whoops. I must have been testing with `--allow-newer`. Thanks for
pointing this out.

Fixed.

**Comment by dmjio** [comment]
:+1: LGTM

**Pull request merged**
