### PR TITLE
Allow text-2.0.*; Haskell CI for GHC 8.0 to 9.2

### PR DESCRIPTION
**Pull request by andreasabel**
Successful CI run at: https://github.com/andreasabel/safecopy/runs/5755961590?check_suite_focus=true

I published this as revision-3 on Hackage: https://hackage.haskell.org/package/safecopy-0.10.4.2/revisions/

### CODE REVIEW

**Comment by stepcut** [comment]
Why the change to the location: in the .cabal file? I am not objecting -- just curious.

**Comment by andreasabel** [comment]
@stepcut: Because github.com does not seem to support `git clone` from such URLs anymore.

**Comment by stepcut** [comment]
Ah -- that is true and sensible. Though maybe changing it to https://github.com/acid-state/safecopy.git would be better? I think the git@github.com only works if you have a github account and have provided ssh keys? This is obviously bikeshedding at this point and not important.

**Comment by andreasabel** [comment]
> Ah -- that is true and sensible. Though maybe changing it to `https://github.com/acid-state/safecopy.git` would be better? I think the `git@github.com` only works if you have a github account and have provided ssh keys? This is obviously bikeshedding at this point and not important.

Well, maybe you are right.  The URL given there is relevant when cloning via `cabal get -s safecopy`.  
- If you don't have github.com setup (with ssh key as you say), then this will fail and you have to get the URL from navigation to the repo (which you can do by clicking on the issue tracker URL from Hackage).
- With a https-url cloning would always succeed, but if you have push rights to the repo, you will probably want to change the `origin` to a `git@github.com` url.  Admittedly, only few will benefit from this.

I'll change it to a https-url.

**Comment by andreasabel** [comment]
OK, here you go: https://hackage.haskell.org/package/safecopy-0.10.4.2/revisions/
(Sorry for the back and forth...)

**Comment by andreasabel** [comment]
@stepcut Anything left to do?

**Comment by stepcut** [comment]
Thanks a ton!

I merged this pull request. But if you are feeling extra generous with your time, the README.md still points to the builds on travis-ci.com. I saw that you added `.github/workflows/haskell-ci.yml`, but I am not sure what else needs to be done to make that do stuff. At the very least we need to update the README.md badges to no longer point at travis?

**Comment by andreasabel** [comment]
> Thanks a ton!

Happy to help!

> I merged this pull request. But if you are feeling extra generous with your time, the README.md still points to the builds on travis-ci.com. 

> I saw that you added `.github/workflows/haskell-ci.yml`, but I am not sure what else needs to be done to make that do stuff. 

It is up and running, see https://github.com/acid-state/safecopy/actions.

> At the very least we need to update the README.md badges to no longer point at travis?

Yes. I can do this.
I noticed that you updated `.travis.yml` (through `haskell-ci`).  Since Travis CI seems to be defunct for this repo, I propose to delete this file.  

Let me do another PR...

**Pull request merged**
